const path=require("path")
const htmlWebpackPlugin=require('html-webpack-plugin')
module.exports={
  entry:path.join(__dirname,'index.js'),
  output:{
    filename:"bundle.js",
    path:path.join(__dirname,'dist')
  },
  module:{
    rules:[
      {
        test:/\.js$/,
        loader:'babel-loader',
        exclude:/node_modules/
      },
      {
        test:/\.html$/,
        loader:'html-loader'
      },
      {
        test:/\.css$/,
        use:[
          'style-loader',
          'css-loader?importLoaders=1',
          {
            loader:'postcss-loader',
            options:{
              ident:'postcss',
              plugins:[
                require('autoprefixer')({
                  browsers:['last 5 versions']
                })
              ]
            }
          }
        ]
      },
      {
        test:/\.less$/,
        use:[
          'style-loader',
          'css-loader',
           {
            loader:'postcss-loader',
            options:{
              ident:'postcss',
              plugins:[
                require('autoprefixer')({
                  browsers:['last 5 versions']
                })
              ]
            }
          },
          'less-loader'
        ]
      },
      {
        test:/\.scss$/,
        use:[
          'style-loader',
          'css-loader',
           {
            loader:'postcss-loader',
            options:{
              ident:'postcss',
              plugins:[
                require('autoprefixer')({
                  browsers:['last 5 versions']
                })
              ]
            }
          },
          'sass-loader'
        ]
      },
      {
        test:/\.(jpg|jpeg|gif|png|svg|ttf)$/i,
        use:[
          {
            loader:'url-loader',
            options:{
              name:'assets/[name]-[hash:5].[ext]',
              limit:10000
            }
          },
            'image-webpack-loader'
        ]
      }
    ]
  },
  plugins:[
    new htmlWebpackPlugin({
      filename:'index.html',
      template:path.join(__dirname,'templ.html')
    })
  ]
}
